// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/src/profile/_children/edit_profile/presenter/widgets/profile_image_picker_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i7;

import 'package:flutter/widgets.dart' as _i5;
import 'package:image_picker/image_picker.dart' as _i8;
import 'package:mobile/core/core.dart' as _i2;
import 'package:mobile/src/shared/models/gif_model.dart' as _i4;
import 'package:mobile/src/shared/services/tenor_gif_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValidationResult_0 extends _i1.SmartFake
    implements _i2.ValidationResult {
  _FakeValidationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MediaPickerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaPickerRepository extends _i1.Mock
    implements _i2.MediaPickerRepository {
  MockMediaPickerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.GifModel?> pickGifFromTenor({
    required _i5.BuildContext? context,
    _i6.TenorGifService? gifService,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickGifFromTenor, [], {
              #context: context,
              #gifService: gifService,
            }),
            returnValue: _i3.Future<_i4.GifModel?>.value(),
          )
          as _i3.Future<_i4.GifModel?>);

  @override
  _i3.Future<_i7.File?> pickImageFromGallery({
    required _i5.BuildContext? context,
    required _i2.MediaPickerConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromGallery, [], {
              #context: context,
              #config: config,
            }),
            returnValue: _i3.Future<_i7.File?>.value(),
          )
          as _i3.Future<_i7.File?>);

  @override
  _i3.Future<_i7.File?> takePhoto({
    required _i5.BuildContext? context,
    required _i2.MediaPickerConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#takePhoto, [], {
              #context: context,
              #config: config,
            }),
            returnValue: _i3.Future<_i7.File?>.value(),
          )
          as _i3.Future<_i7.File?>);

  @override
  _i3.Future<_i2.ValidationResult> validateFile({
    required _i8.XFile? file,
    required _i2.MediaPickerConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateFile, [], {
              #file: file,
              #config: config,
            }),
            returnValue: _i3.Future<_i2.ValidationResult>.value(
              _FakeValidationResult_0(
                this,
                Invocation.method(#validateFile, [], {
                  #file: file,
                  #config: config,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.ValidationResult>);
}
