// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/src/profile/presenter/bloc/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:http/http.dart' as _i3;
import 'package:mobile/core/core.dart' as _i7;
import 'package:mobile/src/profile/domain/models/user.dart' as _i2;
import 'package:mobile/src/profile/profile.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i4.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.User> getCurrentUser(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [token]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getCurrentUser, [token])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateUserProfile(
    String? token,
    Map<String, dynamic>? updates, {
    _i6.File? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserProfile,
              [token, updates],
              {#profilePicture: profilePicture},
            ),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(
                  #updateUserProfile,
                  [token, updates],
                  {#profilePicture: profilePicture},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.User>);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i7.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get accessToken =>
      (super.noSuchMethod(
            Invocation.getter(#accessToken),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#accessToken),
            ),
          )
          as String);

  @override
  String get refreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#refreshToken),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#refreshToken),
            ),
          )
          as String);

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  String get username =>
      (super.noSuchMethod(
            Invocation.getter(#username),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#username),
            ),
          )
          as String);

  @override
  String get userEmail =>
      (super.noSuchMethod(
            Invocation.getter(#userEmail),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#userEmail),
            ),
          )
          as String);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  set accessToken(String? token) => super.noSuchMethod(
    Invocation.setter(#accessToken, token),
    returnValueForMissingStub: null,
  );

  @override
  set refreshToken(String? token) => super.noSuchMethod(
    Invocation.setter(#refreshToken, token),
    returnValueForMissingStub: null,
  );

  @override
  set userId(String? id) => super.noSuchMethod(
    Invocation.setter(#userId, id),
    returnValueForMissingStub: null,
  );

  @override
  set username(String? username) => super.noSuchMethod(
    Invocation.setter(#username, username),
    returnValueForMissingStub: null,
  );

  @override
  set userEmail(String? email) => super.noSuchMethod(
    Invocation.setter(#userEmail, email),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProfileRepositoryAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepositoryAPI extends _i1.Mock
    implements _i4.ProfileRepositoryAPI {
  MockProfileRepositoryAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_1(this, Invocation.getter(#client)),
          )
          as _i3.Client);

  @override
  _i5.Future<_i2.User> getCurrentUser(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [token]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getCurrentUser, [token])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateUserProfile(
    String? token,
    Map<String, dynamic>? updates, {
    _i6.File? profilePicture,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserProfile,
              [token, updates],
              {#profilePicture: profilePicture},
            ),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(
                  #updateUserProfile,
                  [token, updates],
                  {#profilePicture: profilePicture},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.User>);
}
