name: Flutter Tests & Coverage

# Allow runners to get read only access to this repository files(set explicitly now because github requires it)
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Create .env file
        run: |
          echo "TENOR_API_KEY=${{ secrets.TENOR_API_KEY }}" > .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t flutter-tests .

      - name: Run Docker container with tests
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/app \
            -v "$GITHUB_WORKSPACE/.env":/app/.env \
            flutter-tests

      - name: List coverage files
        run: ls -lh coverage

      - name: Upload filtered coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov_filtered.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true


      - name: Clean up .env
        run: rm -f .env
